Vagrant.configure("2") do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.timeout = 300
  config.vm.provider "libvirt" do |lv|
    lv.cpu_mode = 'host-passthrough'
    lv.input :type => "tablet", :bus => "usb"
    lv.graphics_type = "spice"
    lv.video_type = "qxl"
    lv.channel :type => "unix", :target_name => "org.qemu.guest_agent.0", :target_type => "virtio"
    lv.channel :type => "spicevmc", :target_name => "com.redhat.spice.0", :target_type => "virtio"
  end
  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box = "windows-10-amd64"
    vb.gui = false
    vb.default_nic_type = "82545EM"
    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", 2]
    vb.customize ["modifyvm", :id, "--vram", 32]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
  end
end
